quarkus:
  application:
    name: customersAPI
  hibernate-orm:
      database:
        generation: drop-and-create
  datasource:
    jdbc:
      url: jdbc:postgresql://localhost:5432/customers
    db-kind: postgresql
    username: postgres
    password: 9720